export const HEAD = ["adeline.simon31@hotmail.fr", "0621692869","linkedin","github","Télécharger le cv"]
export const ICONS = ["images/mail.png","images/phone.png","images/linkedin.png","images/github.png","images/pdf.png"]
export const QUOTE = ["Faire un bond en avant, je sautille pas","- Perceval, Kaamelott"]
export const TECHNOS = ["ReactJS, "," Material-ui, ","PHP 7, ","Symfony 4, ", "Boostrap"]
export const MENU = ["Expérience", "Formations", "Projets"]