export const SYMFONY = ["Symfony","symfony.png"];
export const REACT = ["ReactJS", "react.png"];
export const GIT = ["GIT","gitlab.png"];
export const ANDROID = ["Android","android.png"]
export const JAVA = ["Java","java.png"];
export const BOOTS = ["Bootstrap", "bootstrap.png"]
export const APIPLAT = ["ApiPlatform","apiplatform.png"]
export const MATERIAL = ["MaterialUI", "material.png"]
export const SQL = ["SQL", "sql.png"]
export const LINUX = ["Ubuntu", "ubuntu.png"]