export const SYMFONY = ["Symfony","symfony.png"];
export const REACT = ["ReactJS", "react.png"];
export const HTML = ["HTML5, CSS3","html.jpg"];
export const GIT = ["GIT","gitlab.png"];
export const ANDROID = ["Android","android.png"]
export const JAVA = ["Java","java.png"];
export const BOOTS = ["Bootstrap", "boostrap.png"]
export const POSTMAN = ["Postman", "postman.png"]
export const APIPLAT = ["ApiPlatform","apiplatform.png"]